version: "3.4"

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  chaos:
    build:
      context: .
      args:
        SERVICE_DIR: ./services/chaos
    volumes:
      - ./services/chaos:/usr/src/app
    ports:
      - "5000:5000"

  gaia:
    build:
      context: .
      args:
        SERVICE_DIR: ./services/gaia
    volumes:
      - ./services/gaia:/usr/src/app
    ports:
      - "5001:5000"
