# frozen_string_literal: true

guard :rspec, cmd: 'rspec' do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$}) { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch(%r{^([^/]+)\.rb$}) { |m| "spec/#{m[1]}_spec.rb" }
end
