version: "3"

services:
  pg-master:
    build: "./db"
    image: "danieldent/postgres-replication"
    restart: "always"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "/var/lib/postgresql/data"
    expose:
      - "5432"

  pg-slave:
    build: "./db"
    image: "danieldent/postgres-replication"
    restart: "always"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      REPLICATE_FROM: "pg-master"
    volumes:
      - "/var/lib/postgresql/data"
    expose:
      - "5432"
    links:
      - "pg-master"

  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
